config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :comments
  end

  root 'nick#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :question
  validates :username, presence: true,
                      length: {minimum: 1}
  validates :description, presence: true

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 2 }
  validates :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @comment = @question.comments.create(comment_params)

    if @comment.save
      redirect_to question_path(@question)
    else
      flash[:notice] = "Error: You must enter a username."
      redirect_to question_path(@question)
    end
  end

  def show
    # @comment = Comment.find(params[:id])
  end

  private
    def comment_params
      params.require(:comment).permit(:username, :description)
    end
end

app/controllers/nick_controller.rb
class NickController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to @question
    else
      flash[:notice] = "Error: Your title must be at least 2 characters long."
      render 'new'
    end
  end

  def show
    @question = Question.find(params[:id])
    @comments = @question.comments
  end

  def index
    @questions = Question.all.order(created_at: :desc)
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      flash[:notice] = "Please fill out form correctly"
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])

    if @question.destroy
      redirect_to questions_path
    else
      render 'show'
    end
  end


  private
  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/nick_helper.rb
module NickHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/nick/index.html.erb
<h1>Welcome To the Jumpoff!</h1>

app/views/questions/edit.html.erb
<%= form_for @question do |f| %>

<%= flash[:notice] %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Delete", question_path(@question), method: :delete %><br>
<%= link_to "Go Back", question_path(@question) %>

app/views/questions/index.html.erb
<%= link_to 'Submit New Question', new_question_path %>

<h1>List of Questions</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>

  <% @questions.each do |question| %>
    <tr>
      <td><%= question.title %></td>
      <td><%= question.description %></td>
      <td><%= link_to 'Show', question_path(question)  %></td>
      <td><%= link_to 'Edit', edit_question_path(question.id) %></td>
      <td><%= link_to "Delete", question_path(question), method: :delete %> </td>
    </tr>
  <% end %>
</table>

app/views/questions/new.html.erb
<h2>Post New Questions</h2>
<%= flash[:notice] %>

<%= form_for @question do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p>
  <strong>Question:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @question.description %>
</p>

<%= link_to 'Edit', edit_question_path(@question.id) %><br>
<%= link_to "Delete", question_path(@question), method: :delete %><br>

<%= flash[:notice] %>

<h2>Add a comment:</h2>
<%= form_for([@question, @comments.build]) do |f| %>
  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %> <%= flash[:notice] %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<ol>
  <% @comments.each do |comment| %>
    <li>Username - <%= comment.username %><br>
    Answer  - <%= comment.description %></li>
  <% end %>
</ol>



<%= link_to 'See All Questions', questions_path %>